### PR TITLE
#508 multiselect context menu for pi objects

### PR DESCRIPTION
**Pull request by peterdew**
Partly addresses #508

# Description

Adds a multiselect contextmenu for Parameter identification object. 
## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

**Review by rwmcintosh — APPROVED** [review]

**Comment by rwmcintosh** [comment]
I'm just going to downgrade some packages besides OSPSuite.Core that were upgraded

**Comment by rwmcintosh** [comment]
> I'm just going to downgrade some packages besides OSPSuite.Core that were upgraded

Disregard, we should be updating these ones anyway, they are all OSPSuite packages with upgrades available

**Comment by msevestre** [comment]
some conflicts here

**Comment by rwmcintosh** [comment]
> some conflicts here

Fixed

**Comment by msevestre** [comment]
can we fix the merge conflicts? Then good to go

**Pull request merged**
