### PR TITLE
#559 removing smart xls

### LINKED ISSUE #559: Replace all the SmartXLS usages that have been left
SmartXLS is still being used in MoBi for import of some things (like Molecule Start Values ). This should be replaced with the use of npoi.

### PR DESCRIPTION
**Pull request by georgeDaskalakis**
closes #559

### CODE REVIEW

**Comment by georgeDaskalakis** [comment]
@msevestre  would there some changes be necessary in this PR before merging?

**Comment by msevestre** [comment]
hum...we haev merged conflicts now..

**Comment by georgeDaskalakis** [comment]
@msevestre fixed. also removed two duplicate references to OSPSuite.Presentation.Importer package from projects.

**Comment by msevestre** [comment]
and go :)

**Pull request merged**
