### PR TITLE
Updated OSPSuite.Core

### PR DESCRIPTION
**Pull request by Yuri05**

### CODE REVIEW

**Review by georgeDaskalakis — APPROVED** [review]

**Comment by georgeDaskalakis** [comment]
@Yuri05 there is a failing test:
MoBi.Core.SBML.PassiveTransportReactionImporterTests.ShouldRaiseOnInvalidFileConvertion

**Comment by Yuri05** [comment]
wtf nothing changed in the SBML area???

**Comment by Yuri05** [comment]
```
Expected: instance of <MoBi.Core.Exceptions.MoBiException>
  But was:  <System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at libsbmlcs.libsbmlPINVOKE.SBMLDocument_setLevelAndVersion__SWIG_2(HandleRef jarg1, Int64 jarg2, Int64 jarg3)
```

might be a bug in libSBML... I will restart the build

**Comment by Yuri05** [comment]
@georgeDaskalakis Ok, rebuild succedded. Must be indeed a bug in libSbml.

**Comment by rwmcintosh** [comment]
> ```
> Expected: instance of <MoBi.Core.Exceptions.MoBiException>
>   But was:  <System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at libsbmlcs.libsbmlPINVOKE.SBMLDocument_setLevelAndVersion__SWIG_2(HandleRef jarg1, Int64 jarg2, Int64 jarg3)
> ```
> 
> might be a bug in libSBML... I will restart the build

This test fails occasionally. Pretty much whenever you look through the MoBi nightly history if it failed, this test is almost always the reason.

**Review by rwmcintosh — APPROVED** [review]

**Comment by georgeDaskalakis** [comment]
> > ```
> > Expected: instance of <MoBi.Core.Exceptions.MoBiException>
> >   But was:  <System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
> >    at libsbmlcs.libsbmlPINVOKE.SBMLDocument_setLevelAndVersion__SWIG_2(HandleRef jarg1, Int64 jarg2, Int64 jarg3)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > might be a bug in libSBML... I will restart the build
> 
> This test fails occasionally. Pretty much whenever you look through the MoBi nightly history if it failed, this test is almost always the reason.

hmm...should we create an issue to keep this under the radar and fix it some time

**Comment by Yuri05** [comment]
yep, I would create an issue and set the test to [Ignore].
I guess the only possible fix would be upgrading of the libSBML (and then hope they have fixed the bug in the meanwhile)

**Pull request merged**
