### PR TITLE
Fixes #1606 Create process option when configuring a simulation

### LINKED ISSUE #1606: Create process option when configuring a simulation

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #1606

# Description
This is just an update that exposes an option to create all process rate parameters for a simulation during simulation creation

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
image

# Questions (if appropriate):

### CODE REVIEW

**Comment by rwmcintosh** [comment]
I could also put the checkbox under the name field instead of beside.

**Comment by rwmcintosh** [comment]
> > I could also put the checkbox under the name field instead of beside.
> 
> looks good for me, would not change

I like the idea of not taking space away from the other controls by placing it on the line below. @PavelBal has another opinion I've heard.

**Comment by PavelBal** [comment]
@rwmcintosh no strong opinion ;)

**Comment by Yuri05** [comment]
> I like the idea of not taking space away from the other controls by placing it on the line below. @PavelBal has another opinion I've heard.

fine for me as well :)

**Review by Yuri05 — APPROVED** [review]

**Pull request merged**
