### PR TITLE
Fixes #1188 When importing SimulationTransfer as Module name the additional building blocks

### LINKED ISSUE #1188: When importing SimulationTransfer as Module instead of add 8 expressions
When there are expressions included in the simulation transfer, 

'Do you want to import 8 expression profiles'

and name them in the dialog.

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #1188 

# Description
In the dialog box we just number the additional building blocks that would be imported, but we can name them for more clarity.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
image

# Questions (if appropriate):

### CODE REVIEW

**Review by msevestre — CHANGES_REQUESTED** [review]
THis is really hard to read. CAn't we add some bullets - tabs or something
We can really do better in terms of formatting these days lol

**Comment by msevestre** [comment]
Exampple from PK-Sim

```

         public static string ProjectFileVersion4IsNotSupportedAnymore(string projectFile)
         {
            var sb = new StringBuilder();
            sb.AppendLine("Support for project file of version 4.2 and older has ended with version 5.6 of the software.");
            sb.AppendLine();
            sb.AppendLine($"In order to convert the file '{projectFile}' to the latest PK-Sim version please proceed as follows:");
            sb.AppendLine();
            sb.AppendLine("  1 - Install an earlier version of PK-Sim (version 5.5 or earlier) and open the file");
            sb.AppendLine("  2 - Save the file");
            sb.AppendLine("  3 - The file is now converted and can be open with any newer version of PK-Sim");
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine("Note: PK-Sim version 4.2 and 5.x or newer can be installed on the same computer without any issues.");
            return sb.ToString();
         }
```

**Comment by rwmcintosh** [comment]
What about just some bullets with indentation
image

One of the awkward things about this list is that we have the ```|``` separator, but they are not always uniform between lines. It depends how many letters in the protein and so on.

**Comment by msevestre** [comment]
it's better but still looks ugly
I think the problem that I still have (not important) is that for an individual it's on one line, and for expression, it's on multiple

if we had sthg like
"Do you also wish to import"
"Individual":
   - XXX
"Expression Profiles":
  - AA
  - BBB
  - CCC

it may look better. not sure

I am approving this now

**Review by msevestre — APPROVED** [review]
approved but ugly

**Comment by rwmcintosh** [comment]
image

**Pull request merged**
